name: Download and Push Model to Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hugging Face CLI
        run: pip install -U "huggingface_hub[cli]"

      - name: Download Model
        run: hf download sentence-transformers/clip-ViT-B-32-multilingual-v1 --local-dir ./clip-multilingual --exclude "onnx/*" "openvino/*" "*.h5" "pytorch_model.bin"

      - name: Zip and Split Model
        run: |
          mkdir -p model_zips
          zip -r model.zip ./clip-multilingual
          zip -s 90m model.zip --out model_zips/model_part
          rm -rf model.zip clip-multilingual

      - name: Commit and Push to Repo
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add model_zips/
          git commit -m "Add split model files (90MB parts)" || echo "No changes to commit"
          git push
